### ISSUE TITLE
The headset cannot be used after being plugged in.

### ISSUE THREAD

**Issue by Lesliewxj** [maxis7567/Hackintosh-Dell-7567-OpenCore_Big-Sur#13]
Everything runs well, but The headset cannot be used after being plugged in.

**Comment by maxis7567** [comment]
open terminal type sudo then drag install.sh from tools/comboJack_Installer then press 'Enter'
Rebuild the cache using sudo kextcache -i /
Reboot

**Comment by Lesliewxj** [comment]
OK, got it. Thanks a lot!
