### ISSUE TITLE
could you make available to Raw or ISO?

### ISSUE THREAD

**Issue by jefersonjuliani** [maxis7567/Hackintosh-Dell-7567-OpenCore_Big-Sur#2]
you could make the system raw to use in balenaetcher because i don't have a mac to download

**Comment by jefersonjuliani** [comment]
if u can provide a download link i would appreciate it very much

**Comment by maxis7567** [comment]
Follow this guide to make your bootable USB 
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html
