### ISSUE TITLE
Fresh Install Big Sur

### ISSUE THREAD

**Issue by 9kinc** [maxis7567/Hackintosh-Dell-7567-OpenCore_Big-Sur#3]
When doing new installation i get error that says 'support.apple.com/mac/startup' .
i have same system as yours . Don't know what is causing this. 
Have you tried new installation?

**Comment by sameeerkashyap** [comment]
@9kinc, I have, just got it working two days ago with a fresh install. Make sure to use the latest EFI and use your UUID using GenSmbios. 

everything works, try resetting your nvram and installing

**Comment by 9kinc** [comment]
What you mean by latest EFI? is that mac boot creation tool you talking about?  Uuids etc are all good, i generate them and i tried almost everything on doc's at opencore and no luck.. it just gets stuck on random things. I will continue tomorrow  also did you make bootable from mac os or windows or linux? i did it from macbook using rhe createmedia

**Comment by sameeerkashyap** [comment]
@9kinc I did it using windows following the OC guide, I mean the latest release 1.0.1

**Comment by maxis7567** [comment]
-1 Set BIOS options properly:
Disable Legacy Option ROMs
Change SATA operation to AHCI (If already using windows, google how to)
Disable Secure Boot
Disable SGX
-2 mount your usb efi partition delete all files. copy efi folder from latest release to usb efi partition and don't change anything
-3 cleannvram restart
4-reset nvram and run installer
you must generate your uuids after a successfull install

**Comment by 9kinc** [comment]
> -1 Set BIOS options properly:
> Disable Legacy Option ROMs
> Change SATA operation to AHCI (If already using windows, google how to)
> Disable Secure Boot
> Disable SGX
> -2 mount your usb efi partition delete all files. copy efi folder from latest release to usb efi partition and don't change anything
> -3 cleannvram restart
> 4-reset nvram and run installer
> you must generate your uuids after a successfull install

ok i will try , any reason why change ids after installation? i usually just change it before

**Comment by maxis7567** [comment]
No reason just I didn't try that.
If you want to change anything in config.plist use ProperTree because opencore config is very sensitive with data Types
https://github.com/corpnewt/ProperTree

**Comment by 9kinc** [comment]
> No reason just I didn't try that.
> If you want to change anything in config.plist use ProperTree because opencore config is very sensitive with data Types
> https://github.com/corpnewt/ProperTree

Yes i do it using properTree, seems like maybe issue withh one of the k texts for battery and light sensor

**Comment by 9kinc** [comment]
![20201207_162836](https://user-images.githubusercontent.com/20781967/101377204-721c0700-38a9-11eb-84dc-c4396f55410d.jpg)

Gets stuck here

**Comment by 9kinc** [comment]
> > No reason just I didn't try that.
> > If you want to change anything in config.plist use ProperTree because opencore config is very sensitive with data Types
> > https://github.com/corpnewt/ProperTree
> 
> Yes i do it using properTree, seems like maybe issue withh one of the k texts for battery and light sensor

i managed to make everything work, it was error with the igpu device properties. Can i ask if your build has iGPU 3D acceleration enabled? if you have you will see transparency under the icons dock. and videos will play without lag, thanks

**Comment by maxis7567** [comment]
yes 3D acceleration is enabled and working good

**Comment by 9kinc** [comment]
> yes 3D acceleration is enabled and working good

i have tried everything past 2 days and graphics driver just fails to register, don't know how to fix in catalina latest version. Did yours work right away or you had to add something for IGPU? thanks

**Comment by maxis7567** [comment]
> > yes 3D acceleration is enabled and working good
> 
> i have tried everything past 2 days and graphics driver just fails to register, don't know how to fix in catalina latest version. Did yours work right away or you had to add something for IGPU? thanks

this guide is for maos bog sur 
if you wana use catalina i suggest try clover bootloader its more compatible
