### ISSUE TITLE
Tested with bigsur 11.2.3

### ISSUE THREAD

**Issue by ricardopacheco** [maxis7567/Hackintosh-Dell-7567-OpenCore_Big-Sur#5]
README and last version works with 11.2.3, just for documented this.

**Comment by maxis7567** [comment]
tanks

**Comment by maxis7567** [comment]
> README and last version works with 11.2.3, just for documented this.

Did you update it to 11.2.3 or installed with an image file

**Comment by ricardopacheco** [comment]
@maxis7567 Fresh setup with vanilla image.

**Comment by mishailovic** [comment]
> @maxis7567 Fresh setup with vanilla image.

Just in time 🤣

Btw, can confirm that EFI works with latest available bigsur image
