### ISSUE TITLE
WifiCard Recommendations?

### ISSUE THREAD

**Issue by ffvieira18** [maxis7567/Hackintosh-Dell-7567-OpenCore_Big-Sur#6]
My friend, excellent guide!
I read in some guides that the factory wifi does not work in hackintosh.
Would you like to know which wifi card you are using on dell 7567?

**Comment by maxis7567** [comment]
90% of this model have intel 3165 Wi-Fi card and its work with airportitlwm driver i put in kext folder
if you have other kind of Wi-Fi card tell me

**Comment by ffvieira18** [comment]
Unfortunately it is a Qualcomm QCA61x4A 802.11ac. 
It seems that it is not compatible with hackintosh. I'm looking for a model to buy on aliexpress, but I don't know which one would be compatible with the dell 7567.

maybe BCM94360NG WIFI Card NGFF M.2 1200Mbps Bluetooth4.0 NGFF 802.11ac

**Comment by maxis7567** [comment]
Dell Wireless DW1560 is a good choice, but it's expensive
I'm using Intel 3165 Wi-Fi network working well, but Bluetooth have problem with some device

**Comment by ffvieira18** [comment]
Maxis, i bought the wifi, i am waiting for delivery. Sometimes the sound makes a noise that makes me scared, like a gunshot. Is there any way to fix this?

**Comment by maxis7567** [comment]
i don't know anything about the noise
its from speakers?

**Comment by ffvieira18** [comment]
Is the speaker, I think the subwoofer!

**Comment by maxis7567** [comment]
do you know how to config OC plist ?
if you can change audio layout_id to 13 save and reboot and in boot menu rest nvram
it should disable your subwoofer

**Comment by ffvieira18** [comment]
I knew how to configure a little bit by the clover configurator.
It's my first time using opencore, I only use opencore tutorial to create usb on windows, i used the propertree software on windows to remove scanpolicy from your config.plist file and i follow this guide https://www.youtube.com/watch?v=dovJUlKgS5E&ab_channel=V-TechChannel to generate  mac serial, uuid and smbios Macbookpro14,1.
I don't know how to change values ​​in config.plist in macos.

**Comment by maxis7567** [comment]
it is totally different dont open that file with clover configrator

**Comment by maxis7567** [comment]
replace this file in EFI OC folder then reboot and reset nvram
https://1drv.ms/u/s!AvY0lepIMd6lmWWdHXnU-xSl2iwy?e=2todmo

**Comment by ffvieira18** [comment]
It worked! =D 
Do i need to do the video tutorial (mac serial, uuid and smbios) again?

**Comment by maxis7567** [comment]
uuid isn't necessary but if you want to use mac apps like imessage you must do it

**Comment by ffvieira18** [comment]
Thanks for helping maxis!
