### ISSUE TITLE
No audio - Big Sur 11.2.3

### ISSUE THREAD

**Issue by matheusferreira195** [maxis7567/Hackintosh-Dell-7567-OpenCore_Big-Sur#7]
Hi guys! FInished installing Big Sur 11.2.3, without any problems, except the audio not working. The headphone jack doesn't work, as the spearkers. Bluetooth headphones work fine tho.  I runned the fix on the tools folder but it didn't fixed the problem. The system detects the headphones when I plug them, but no sound. The volume slider is greyed out also.

Any tips on how to solve this? I tried already setting different layouts for alc256 on the config.plist.

**Comment by maxis7567** [comment]
you must reset nvram to layout_id changes to take effect

**Comment by matheusferreira195** [comment]
> you must reset nvram to layout_id changes to take effect

You're the best! It worked!

**Comment by maxis7567** [comment]
after resetting nvram your uuid will be deleted config uuid again
